
# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

[character]
success_symbol = "[\uf054](#50fa7b)" # 
vicmd_symbol = "[\ue62b](white)" # 
error_symbol = "[\uf467](#ff5555)" # 

[line_break]
disabled = false

#[directory]
#style = "#8be9fd bold"
#truncation_length = 2
[directory]
truncation_length = 2
#truncation_symbol = "…/"
truncate_to_repo = false

[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

[git_branch]
disabled = false
symbol = " "
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_status]
conflicted = "[󰕚 ](#ff5555)"
ahead = "[ ${count} ](#50fa7b)"
behind = "[ ${count} ](#ff5555)"
diverged = "[󰙁  ${ahead_count} ${behind_count}](#00FFFF)"
untracked = "[ ${count} ](#ffb86c)"
stashed = "[  ](#50fa7b)"
modified = "[ ${count} ](#bd93f9)"
staged = "[ ${count} ](#50fa7b)"
renamed = "[ ${count} ](#bd93f9)"
deleted = "[ ${count} ](#ff5555)" 
format = "$all_status$ahead_behind"

[java]
disabled = true

[gradle]
disabled = true

[lua]
disabled = true

[haskell]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

