--vim.g.blamer_enabled = true
--vim.g.blamer_delay = 500
--vim.g.blamer_relative_time = true
--vim.g.blamer_show_in_visual_modes = false
--vim.g.blamer_show_in_insert_modes = false

--require("blame_line").setup {
  --show_in_visual = false,
  --show_in_insert = false,
  --prefix = "             ",
  --template = "<author> • <author-time> • <summary>",
  --date = {
    --relative = true,
    --format = "%d-%m-%y",
  --},
  --hl_group = "BlameLineNvim",
  --delay = 1000,
--}

--require("blame_line").setup {
  --show_in_visual = false,
  --show_in_insert = false,
  --prefix = "             ",
  --template = "<author> • <author-time> • <summary>",
  --date = {
    --relative = true,
    --format = "%d-%m-%y",
  --},
  --hl_group = "BlameLineNvim",
  --delay = 1000,
--}
